name: My CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This is lint job, it will run ESLint on the codebase to check for any linting errors
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true 

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm test

      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/
          retention-days: 1
  
  sonarqube-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

      - name: setup sonar-scanner
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=harshithkumartech-source_devops-practice
            -Dsonar.organization=harshithkumartech-source
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,coverage/**
     
  
