name: MyFirst pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello!"
      - name: lsit all the files
        run: ls -ltr
  
  
